### ISSUE TITLE
Use parameters in sync.sh as per datapub project, e.g. nhs, gdx.

### ISSUE THREAD

**Issue by mbeilin** [datopian/ckanext-datapub#2]
We need sync.sh file to be parametrized as per datapub project, for example for NHS it should look like this, while we are fetching `datapub-nhs` or just `nhs` from config.

(for datapub-nhs - https://github.com/datopian/datapub-nhs)

```
git clone git@github.com:datopian/datapub-nhs.git
cd datapub-nhs
yarn
yarn build
cd -
rm -r ckanext/datapub/fanstatic/**/*
cp -r datapub-nhs/build/static/* ckanext/datapub/fanstatic/
```

## Acceptance

- [ ] `sync.sh` is parametrized **with what**

## Tasks

- [ ] Set up variable in config to point to specific datapub project
- [ ] `sync.sh` uses datapub specific project name as config variable

**Comment by anuveyatsu** [comment]
is this a blocker @mbeilin @mariorodeghiero ?

**Comment by mbeilin** [comment]
> is this a blocker @mbeilin @mariorodeghiero ?

yes, for NHS.
Atm I just override this in sep branch, so we can use it in Staging env - https://github.com/datopian/ckanext-datapub/blob/datapub-nhs/sync.sh

**Comment by mariorodeghiero** [comment]
not for me, I'm doing manually because I using locally for while.

**Comment by mariorodeghiero** [comment]
@mbeilin @anuveyatsu Irakli did some changes in the sync.sh file to execute everything automatically, and also to be able to insert the chunks in `upload_module.html`. So please take a look at these changes https://github.com/datopian/ckanext-datapub/pull/4 because I will be helpful for NHS
